"""add personal saved queries"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision = "b5200e225547"
down_revision = "c4077a680bc5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_queries",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "sql", sa.Text().with_variant(mysql.LONGTEXT(), "mysql"), nullable=False
        ),
        sa.Column("connection_id", sa.Integer(), nullable=True),
        sa.Column("database", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_saved_queries_user_updated",
        "saved_queries",
        ["user_id", "updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_saved_queries_user_updated", table_name="saved_queries")
    op.drop_table("saved_queries")
    # ### end Alembic commands ###
