"""allow large SQL text"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = "bda5fd897bc1"
down_revision = "9a2037cf17b0"
branch_labels = None
depends_on = None


def upgrade():
    if op.get_bind().dialect.name != "mysql":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "executions",
        "sql",
        existing_type=mysql.TEXT(),
        type_=sa.Text().with_variant(mysql.LONGTEXT(), "mysql"),
        existing_nullable=False,
    )
    op.alter_column(
        "statements",
        "sql",
        existing_type=mysql.TEXT(),
        type_=sa.Text().with_variant(mysql.LONGTEXT(), "mysql"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().dialect.name != "mysql":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "statements",
        "sql",
        existing_type=sa.Text().with_variant(mysql.LONGTEXT(), "mysql"),
        type_=mysql.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "executions",
        "sql",
        existing_type=sa.Text().with_variant(mysql.LONGTEXT(), "mysql"),
        type_=mysql.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
